### ISSUE TITLE
Don't use Time.now in Ruby

### ISSUE THREAD

**Issue by chrisseaton** [kostya/jit-benchmarks#3]
The Ruby benchmarks are using `Time.now` to measure time. The problem with this is that this clock is not *monotonic* - that means it may unpredictably move both forward and backward in time while the program is running. I'd recommend you always use `Process.clock_gettime(Process::CLOCK_MONOTONIC)` as a drop-in replacement for `Time.now` for this purpose. `CLOCK_MONOTONIC` always moves steadily in the same direction.

**Comment by kostya** [comment]
Script time already measure by CLOCK_MONOTONIC, Time - internal measure (which teoretically exclude load env, and others). I think i will add monotonic to internal measure too.

**Comment by kostya** [comment]
fixed, all things measured by external ruby process with CLOCK_MONOTONIC
