### ISSUE TITLE
No warmup?

### ISSUE THREAD

**Issue by ahorek** [kostya/jit-benchmarks#4]
if you want to test jit performace, you should take a warmup time into account.

a good jit needs some time to optimize the code. Short scripts like this take just a second to execute. Obviousely, languages without any jit or with a lightweight jit (which on the other hand optimizes the code poorely) will win the challange. I don't think it's fair.

for example

Matmul (your results)
```
Ruby 	JRuby 	155.08
Ruby3 		75.98
Ruby3 	JIT 	61.74
Ruby 	GraalVM 6.75
```

Matmul (my results)
```
Ruby 	JRuby	16.78 + indy

Ruby 	JRuby 	24.30
Ruby3 		21.92
Ruby3 	JIT 	22.02
Ruby 	GraalVM 3.90
```

as you can see, in your case jruby is 2 times slower then ruby 3, but after warmup, the performance is comparable. It even beats cruby if we turn -Xcompile.invokedynamic=true on.

yes, warmup time is also important, but it should be more clear what we're mesuring.

**Comment by eregon** [comment]
IMHO it's OK to measure without warmup before, as long as it's clear the results are "the time it takes to run the benchmark once".
In reality, people don't run such short scripts repetitively in a loop, so running it once seems a decent way to measure them (but arguably AOT compilation time should be counted somehow :p).

**Comment by eregon** [comment]
That said, it would be interesting to have both numbers, i.e., how long the first iteration took, and what's the peak performance like.
That would be more useful to compare e.g. Ruby to C or Crystal, which is otherwise unfair because they have extra time before to compile.

**Comment by ahorek** [comment]
_The goal of the benchmark is to find the most successful JIT solutions._

I don't think the best JIT solution should be selected by a measurement on a short script. In such case, the best JIT is no JIT. These benchmarks are measuring a warmup time or AOT, not how good the JIT solution is.
Implementation that actually do JIT the code looks very bad in this benchmark, but the performance might be very different after some warmup.

a fair jit benchmark should measure
**script time** (this benchmark, start -> end)
**warmup time** (run a script in a loop, measure the time from start until the peak performance is achived)
**peak performance** (a loop after warmup)

**Comment by eregon** [comment]
> In such case, the best JIT is no JIT.

That's not true (e.g., https://eregon.me/blog/2018/02/19/truffleruby-native-fast-short-scripts.html).

> a fair jit benchmark should measure
> **script time** (this benchmark, start -> end)
> **warmup time** (run a script in a loop, measure the time from start until the peak performance is achived)
> **peak performance** (a loop after warmup)

Agreed that would be the best and show all important facets of the JIT.
Detecting warmup time reliably might be quite difficult, so I think `script time` and `peak performance` would already be great, and more useful *to find the most successful JIT solutions*.

**Comment by ahorek** [comment]
_That's not true (e.g., https://eregon.me/blog/2018/02/19/truffleruby-native-fast-short-scripts.html)._
Sure, AOT is a huge improvement for a startup time. Thanks for pointing out that article.

_Detecting warmup time reliably might be quite difficult_
👍 it would be interesting to have a warmup charts and compare them cross implementations.

**Comment by kostya** [comment]
i would think about it, how many iterations needed for warmup usually? is enought 2?

**Comment by ahorek** [comment]
well, it depends on the code and the hw, but here's a quick test.

### binary trees

ruby 3.0.0 + jit
**time(3.5772426)
time(2.6413509)
time(2.3079011)**
time(2.4258082)
time(2.4663808)
time(2.4245468)
time(2.3165205)
time(2.35117)

jruby 9.2.14.0 + indy
**time(2.448579)
time(1.067399)
time(1.310856)
time(1.112174)
time(1.022192)
time(0.878929)**
time(0.875077)
time(0.9554039999999999)
time(0.8994420000000001)

jruby 9.2.14.0
**time(2.59485)
time(1.769797)**
time(1.77251)
time(1.697259)
time(1.679875)
time(1.723285)
time(1.736062)
time(1.810352)
time(1.82088)
time(1.730321)

truffleruby 20.3.0
**time(7.156)
time(0.494)**
time(0.464)
time(0.44299999999999995)
time(0.47000000000000003)
time(0.4099999999999999)
time(0.453)
time(0.46799999999999997)
time(0.42200000000000004)
time(0.441)
time(0.4139999999999999)
time(0.45)


### matmul
ruby 3.0.0 + jit
**time(0.2057361)
time(0.1753279)**
time(0.1748168)
time(0.1743921)
time(0.154534)
time(0.2253573)
time(0.2050425)

jruby 9..2.14.0
**time(0.732015)
time(0.294435)
time(0.224298)**
time(0.212698)
time(0.289786)
time(0.17868799999999999)
time(0.20368999999999998)

jruby 9.2.14.0 + indy
**time(0.809161)
time(0.332092)
time(0.297064)
time(0.19236)
time(0.20599699999999999)
time(0.197642)
time(0.159001)
time(0.14321899999999999)**
time(0.238087)
time(0.141091)
time(0.14901499999999998)
time(0.14028200000000002)
time(0.154177)

truffleruby 20,3,0
**time(0.646)
time(0.016)**
time(0.018000000000000002)
time(0.015000000000000001)
time(0.013000000000000001)
time(0.030000000000000002)
time(0.032)
time(0.029999999999999916)
time(0.034)
time(0.029)


JRuby has a long warmup time, especially with indy on, it takes time to stabilize.
TruffleRuby (AOT) starts slow, but it optimize very quickly.

**Comment by kostya** [comment]
what is jruby + indy?

my result for binarytree, 5 runs


## Binarytrees
| Language   | Interpreter | Best Time, s | Run Times, s                      | Script Time, s | Memory, Mb |
|------------|-------------|--------------|-----------------------------------|----------------|------------|
| C++        | g++         | 1.01         | 1.03, 1.01, 1.03, 1.03, 1.02      | 5.16           | 34.9       |
| Crystal    |             | 1.30         | 1.30, 1.31, 1.32, 1.36, 1.34      | 6.63           | 49.1       |
| Ruby       | GraalVM_JVM | 1.61         | 5.75, 1.66, 1.66, 1.63, 1.61      | 13.97          | 1255.7     |
| Python3    | Cython      | 2.01         | 2.02, 2.01, 2.12, 2.15, 2.40      | 10.74          | 40.1       |
| C          | gcc         | 2.28         | 2.34, 2.38, 2.28, 2.34, 2.41      | 11.75          | 97.7       |
| Ruby       | GraalVM     | 2.63         | 3.81, 2.63, 2.68, 2.72, 2.69      | 14.58          | 858.6      |
| Ruby       | Topaz       | 3.58         | 3.85, 3.58, 3.66, 3.64, 3.58      | 18.34          | 111.1      |
| Javascript | GraalVM_JVM | 3.86         | 5.98, 3.99, 3.86, 3.88, 3.86      | 23.92          | 1375.9     |
| Javascript | Node        | 3.95         | 4.26, 4.27, 4.12, 4.10, 3.95      | 20.81          | 289.4      |
| Javascript | GraalVM     | 5.73         | 6.85, 5.76, 6.06, 5.73, 5.83      | 30.37          | 1120.8     |
| Ruby       | JRuby       | 6.56         | 6.89, 6.60, 6.58, 6.61, 6.56      | 34.31          | 682.4      |
| Python3    | GraalVM_JVM | 6.57         | 28.41, 11.70, 6.71, 6.72, 6.57    | 65.74          | 1780.5     |
| Ruby3      | JIT         | 9.50         | 9.67, 9.73, 9.61, 9.50, 9.62      | 48.18          | 89.9       |
| Python3    | Pypy        | 10.52        | 10.74, 10.54, 10.61, 10.52, 10.61 | 53.04          | 196.9      |
| Python2    | Pypy        | 11.12        | 11.24, 11.20, 11.26, 11.12, 11.17 | 56.02          | 220.5      |
| Python3    | GraalVM     | 12.39        | 18.14, 13.82, 12.39, 12.67, 12.50 | 69.62          | 1539.0     |
| Ruby       | JIT         | 13.41        | 13.48, 13.41, 13.51, 13.54, 13.60 | 67.58          | 55.2       |
| Ruby3      |             | 13.52        | 13.67, 13.66, 13.63, 13.53, 13.52 | 68.05          | 104.2      |
| Ruby       |             | 14.36        | 14.64, 14.62, 14.41, 14.36, 14.39 | 72.45          | 82.7       |
| Lua        | JIT         | 18.25        | 18.26, 18.59, 18.25, 18.67, 18.83 | 92.70          | 509.7      |
| Ruby       | rbx         | 35.34        | 35.98, 35.50, 35.34, 35.39, 35.37 | 177.75         | 614.3      |
| Lua        |             | 49.99        | 49.99, 53.25, 55.07, 53.05, 56.77 | 268.33         | 355.3      |
| Python3    | Nuitka      | > 300        | > 300                             | > 300          | 205.5      |
| Python2    |             | > 300        | > 300                             | > 300          | 405.5      |
| Python3    |             | > 300        | > 300                             | > 300          | 202.9      |
| Python2    | Jython      | > 300        | > 300                             | > 300          | 1742.6     |

**Comment by ahorek** [comment]
> what is jruby + indy?

it's an additional option
https://github.com/jruby/jruby/wiki/PerformanceTuning
```
jruby -Xcompile.invokedynamic=true -S script.rb
```

it may significantly improve peak performance of cpu intensive tasks (like binary trees), but at the cost of longer warmup time. It's disabled by default.

**Comment by eregon** [comment]
@kostya The runs above seem done in different processes, which is probably why the numbers look very similar.
For warmup, it is necessary to run the benchmark multiple times in the same process.

**Comment by eregon** [comment]
If the runs in https://github.com/kostya/jit-benchmarks/issues/4#issuecomment-751878030 were done in the same process, then it seems you need more than 5 iterations with your processor or this VirtualBox+Docker setup.
It seems >4x slower than the numbers reported by @ahorek above, that seems a lot if executed on a AMD Ryzen 7 3800X.

> surprisingly on Windows it sometimes even faster

Isn't that somewhat expected since that's the host OS?

**Comment by kostya** [comment]
runs is 5 iterations on one process, numbers different because we run with different argument. i run more tests in this branch: https://github.com/kostya/jit-benchmarks/tree/multiple_runs

**Comment by eregon** [comment]
I see, looking into the numbers in more details, it does seem to warmup up, notably for GraalVM_JVM runs.
Probably some of the warmup already happens during the first run, because it is longer, I guess due to the higher value for the arguments.

**Comment by eregon** [comment]
The results above for Binarytrees, I think that should solve this issue :smiley:

**Comment by ahorek** [comment]
thanks @kostya LGTM!

**Comment by kostya** [comment]
Multiple runs in master now.

**Comment by kostya** [comment]
jruby indy also added.
