### ISSUE TITLE
add mypyc, the official static-type python to C compiler

### ISSUE THREAD

**Issue by aploium** [kostya/jit-benchmarks#6]
Mypy is a (official) static type checker for Python.

And mypyc are official python to C compiler, build on top of mypy, they said it would give 2-10x performance gain. And they use mypyc to compile mypy itself to get 4x performance gain. Could you please add this for test?

https://github.com/python/mypy
https://github.com/mypyc/mypyc

**Comment by kostya** [comment]
Added, btw some tests crashed, and memory usage seems measured not correctly.
